name: Deploy App Configuration
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'No hace nada'
        required: false
        default: 'false'
  push:
    branches:
      - main
      - develop
    paths:
      - app/config/**
jobs:
  change-config-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: |
          pip install requests

      - name: Call /refresh service
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
          NORTHFLANK_API_KEY: ${{ secrets.NORTHFLANK_API_KEY }}
          NORTHFLANK_PROJECT_ID: ${{ vars.NORTHFLANK_PROJECT_ID }}
          NORTHFLANK_SERVICE_ID: ${{ vars.NORTHFLANK_SERVICE_ID }}
        shell: python
        run: |
          import os
          import requests

          HEADERS = {
            "Authorization": f"Bearer {os.environ['NORTHFLANK_API_KEY']}",
            "Content-Type": "application/json"
          }

          project_id = os.environ['NORTHFLANK_PROJECT_ID']
          service_id = os.environ['NORTHFLANK_SERVICE_ID']

          resp = requests.get(
            f"https://api.northflank.com/v1/projects/{project_id}/services/{service_id}",
            headers=HEADERS
          )
          resp.raise_for_status()
          url = resp.json()["data"]["ports"][0]["dns"]
          print(f"Service URL: {url}")
          refresh_resp = requests.post(f"https://{url}/actuator/refresh")
          print(f"Respuesta /actuator/refresh: {refresh_resp.status_code} - {refresh_resp.text}")

