on:
  workflow_call:
    inputs:
      NAME:
        description: "Name"
        required: true
        type: string
    outputs:
      DEPLOY_TAG:
        description: "Result of the workflow"
        value: "${{ jobs.deploy-tag.outputs.DEPLOY_TAG }}"
jobs:
  deploy-tag:
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_TAG: ${{ steps.deploy-tag.outputs.DEPLOY_TAG }}
    steps:
      - name: Preparar nombre de repositorio en minúsculas
        id: deploy-tag
        run: |
          echo "DEPLOY_TAG=ghcr.io/${GITHUB_REPOSITORY@L}-${{ inputs.NAME }}:${{ github.sha }}" >> ${GITHUB_OUTPUT}

